# Form implementation generated from reading ui file 'chatapp.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 589)
        MainWindow.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.05 rgba(14, 8, 73, 255), stop:0.19774 rgba(126, 14, 81, 255), stop:0.548023 rgba(68, 207, 145, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255), stop:1 rgba(82, 213, 0, 255))")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.messagearea = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.messagearea.setGeometry(QtCore.QRect(20, 130, 391, 371))
        self.messagearea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.messagearea.setObjectName("messagearea")
        self.messagetxt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.messagetxt.setGeometry(QtCore.QRect(20, 510, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.messagetxt.setFont(font)
        self.messagetxt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.messagetxt.setObjectName("messagetxt")
        self.connectbtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connectbtn.setGeometry(QtCore.QRect(190, 60, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(36)
        self.connectbtn.setFont(font)
        self.connectbtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.BusyCursor))
        self.connectbtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.connectbtn.setCheckable(False)
        self.connectbtn.setObjectName("connectbtn")
        self.send = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send.setGeometry(QtCore.QRect(460, 510, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.send.setFont(font)
        self.send.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.send.setCheckable(False)
        self.send.setObjectName("send")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chatroom"))
        self.messagetxt.setPlaceholderText(_translate("MainWindow", "Type your message here.............................."))
        self.connectbtn.setText(_translate("MainWindow", "Connect"))
        self.send.setText(_translate("MainWindow", "send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
